-- Deprecated legacy reference.
-- The active database model for Andres English Tutor now lives in:
--   supabase/migrations/
--
-- This file is kept only to preserve project history from the original Learna
-- prototype. Do not apply it to a production Supabase project.
